### ISSUE TITLE
Refactor ReactiveClient code

### ISSUE THREAD

**Issue by patricknoir** [patricknoir/reactive-system#17]
Currently the ReactiveClient is using actor base implementation and the KafkaProducer is blocking the thread which is not acceptable.

As part of this task evaluate the possibility to implement the client using Akka Stream.

- [x] Implement the client using Akka Stream
- [x] Refactor tests
- [ ] Document the Client Design document in paradox website
- [x] Implement One Way Message

**Comment by jlescanciano** [comment]
The following pull request solve the ticket: #20
