### ISSUE TITLE
Simplifying the Reactive System Algebra from Future[Xor[Error, A]] to a Future[A]

### ISSUE THREAD

**Issue by patricknoir** [patricknoir/reactive-system#7]

**Comment by mlosiewicz-pl** [comment]
How about having Future.successful or Future.failed on API level and do not expose Xor outside?

**Comment by patricknoir** [comment]
Agree with Michal to simplify the API by removing the inner Xor[...], originally designed to separate business logic error from future, there is no need of such distinction, the failure of the future will tell me that and we will avoid to use monads transformers.

**Comment by patricknoir** [comment]
Ready for code review.
